apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-unprivileged
  name: nginx-unprivileged
spec:
  ports:
  - name: 1025-1025
    port: 1025
    protocol: TCP
    targetPort: 1025
  selector:
    app: nginx-unprivileged
  type: ClusterIP
status:
  loadBalancer: {}
